### Create Trip
POST http://localhost:8080/trips
Content-Type: application/json

{
  "destination": "Florianópolis, SC",
  "starts_at": "2024-07-15T10:30:00Z",
  "ends_at": "2024-07-19T12:00:00Z",
  "emails_to_invite": ["mayk.brito@rocketseat.com"],
  "owner_name": "Fernanda Kipper",
  "owner_email": "fernanda.kipper@rocketseat.com"
}

### Trip Id
@tripId = abcf488b-bf51-458b-a717-28ef83020508

### Get trip by ID
GET http://localhost:8080/trips/{{tripId}}

### Update trip by ID
PUT http://localhost:8080/trips/{{tripId}}
Content-Type: application/json

{
  "destination": "Porto Alegre, RS",
  "starts_at": "2024-07-17T10:30:00Z",
  "ends_at": "2024-07-22T12:00:00Z"
}

### Confirm trip by ID
GET http://localhost:8080/trips/{{tripId}}/confirm

### Get participants by trip ID
GET http://localhost:8080/trips/{{tripId}}/participants

### Invite participant
POST http://localhost:8080/trips/{{tripId}}/invite
Content-Type: application/json

{
  "email": "diego.fernandes@rocketseat.com"
}

### Participant ID
@participantId = 7abaecb5-c879-4954-b262-86b77a5e70ea

### Confirm participant by ID
PATCH http://localhost:8080/participants/{{participantId}}/confirm
Content-Type: application/json

{
  "name": "Mayk Brito"
}

### Create trip activity
POST http://localhost:8080/trips/{{tripId}}/activities
Content-Type: application/json

{
  "title": "Check-in no hotel",
  "occurs_at": "2024-07-17T12:00:00Z"
}

### List trip activities
GET http://localhost:8080/trips/{{tripId}}/activities


### Create trip link
POST http://localhost:8080/trips/{{tripId}}/links
Content-Type: application/json

{
  "title": "O que fazer: Florianópolis",
  "url": "https://www.tripadvisor.com.br/Attractions-g303576-Activities-Florianopolis_State_of_Santa_Catarina.html"
}

### List trip link 
GET http://localhost:8080/trips/{{tripId}}/links
