### Create Trip
POST http://localhost:8080/trips
Content-Type: application/json

{
  "destination": "Florianópolis, SC",
  "starts_at": "2024-07-15T10:30:00.0000",
  "ends_at": "2024-07-19T12:00:00.0000",
  "emails_to_invite": ["mayk.brito@rocketseat.com"],
  "owner_name": "Fernanda Kipper",
  "owner_email": "fernanda.kipper@rocketseat.com"
}

### tripId
@tripId = ff1ea6e8-1782-4fd3-b722-d134f9d23aa4

### Get trip by ID
GET http://localhost:8080/trips/{{tripId}}

### Update trip by ID
PUT http://localhost:8080/trips/{{tripId}}
Content-Type: application/json

{
  "destination": "Porto Alegre, RS",
  "starts_at": "2024-07-17T10:30:00.0000",
  "ends_at": "2024-07-22T12:00:00.0000"
}

### Confirm trip by ID
GET http://localhost:8080/trips/{{tripId}}/confirm
