### Create trip
POST http://localhost:8080/trips
Content-Type: application/json

{
  "destination": "Florianópolis, SC",
  "starts_at": "2024-07-24T10:30:00Z",
  "ends_at": "2024-07-29T12:00:00Z",
  "emails_to_invite": ["mayk.brito@email.com", "rodrigo.goncalves@email.com"],
  "owner_name": "Fernanda Kipper",
  "owner_email": "fernanda.kipper@email.com"
}

### Trip Id
@tripId = 313a57c7-2a1c-495e-a67f-4de21c379e31

### Get trip by ID
GET http://localhost:8080/trips/{{tripId}}

### Update trip by ID
PUT http://localhost:8080/trips/{{tripId}}
Content-Type: application/json

{
  "destination": "Porto Alegre, RS",
  "starts_at": "2024-07-25T10:30:00Z",
  "ends_at": "2024-07-29T12:00:00Z"
}

### Confirm trip by ID
GET http://localhost:8080/trips/{{tripId}}/confirm

### Get trip participants
GET http://localhost:8080/trips/{{tripId}}/participants

### Invite participant
POST http://localhost:8080/trips/{{tripId}}/invites
Content-Type: application/json

{
  "email": "diego.fernandes@email.com"
}

### Participant ID
@participantId = f6011ab0-9d32-477c-95fd-9db358e2012a

### Confirm participant by ID
POST http://localhost:8080/participants/{{participantId}}/confirm
Content-Type: application/json

{
  "name": "Mayk Brito",
  "email": "mayk.brito@mail.com"
}

### Create trip activity
POST http://localhost:8080/trips/{{tripId}}/activities
Content-Type: application/json

{
  "title": "Check-in no hotel",
  "occurs_at": "2024-07-17T12:00:00Z"
}

### Create trip activity 2
POST http://localhost:8080/trips/{{tripId}}/activities
Content-Type: application/json

{
  "title": "Jantar",
  "occurs_at": "2024-07-17T20:00:00Z"
}

### Create trip activity 3
POST http://localhost:8080/trips/{{tripId}}/activities
Content-Type: application/json

{
  "title": "Café da manhã",
  "occurs_at": "2024-07-18T07:30:00Z"
}

### List trip activities
GET http://localhost:8080/trips/{{tripId}}/activities


### Create trip link
POST http://localhost:8080/trips/{{tripId}}/links
Content-Type: application/json

{
  "title": "O que fazer: Florianópolis",
  "url": "https://www.tripadvisor.com.br/Attractions-g303576-Activities-Florianopolis_State_of_Santa_Catarina.html"
}

### List trip link 
GET http://localhost:8080/trips/{{tripId}}/links

# Error tests

### 404 NoResourceFoundException
GET http://localhost:8080/not_found

### 405 HttpRequestMethodNotSupportedException
GET http://localhost:8080/trips

### 400 MethodArgumentTypeMismatchException
GET http://localhost:8080/trips/invalid-uuid

### 415 HttpMediaTypeNotSupportedException
POST http://localhost:8080/trips
Content-Type: application/soap+xml

### 400 HttpMessageNotReadableException
POST http://localhost:8080/trips/{{tripId}}/activities
Content-Type: application/json

{
  "title": "Café da manhã",
  "occurs_at": "2024-07-18T07:30:00Z",
}

# Validation tests

### 400 TripCreateRequestPayload
POST http://localhost:8080/trips
Content-Type: application/json

{
  "destination": "",
  "starts_at": "",
  "ends_at": "",
  "emails_to_invite": [],
  "owner_name": "",
  "owner_email": "fernanda.kipper#email.com"
}

### 400 TripCreateRequestPayload 2
POST http://localhost:8080/trips
Content-Type: application/json

{
  "destination": "Florianópolis, SC",
  "starts_at": "2024-07-15T10:30:00Z",
  "ends_at": "2024-07-29T12:00:00Z",
  "emails_to_invite": ["mayk.brito@email.com", "rodrigo.goncalves@email.com"],
  "owner_name": "Fernanda Kipper",
  "owner_email": "fernanda.kipper@email.com"
}

### 400 TripCreateRequestPayload 3
POST http://localhost:8080/trips
Content-Type: application/json

{
  "destination": "Florianópolis, SC",
  "starts_at": "2024-07-25T10:30:00Z",
  "ends_at": "2024-07-25T10:00:00Z",
  "emails_to_invite": ["mayk.brito@email.com", "rodrigo.goncalves@email.com"],
  "owner_name": "Fernanda Kipper",
  "owner_email": "fernanda.kipper@email.com"
}

### 400 TripUpdateRequestPayload 1
PUT http://localhost:8080/trips/{{tripId}}
Content-Type: application/json

{
  "destination": "",
  "starts_at": "",
  "ends_at": ""
}

### 400 TripUpdateRequestPayload 2
PUT http://localhost:8080/trips/{{tripId}}
Content-Type: application/json

{
  "destination": "Florianópolis, SC",
  "starts_at": "2024-07-15T10:30:00Z",
  "ends_at": "2024-07-29T12:00:00Z"
}

### 400 TripUpdateRequestPayload 3
PUT http://localhost:8080/trips/{{tripId}}
Content-Type: application/json

{
  "destination": "Florianópolis, SC",
  "starts_at": "2024-07-25T10:30:00Z",
  "ends_at": "2024-07-25T10:00:00Z"
}

### 400 ParticipantRequestPayload
POST http://localhost:8080/participants/{{participantId}}/confirm
Content-Type: application/json

{
  "name": "",
  "email": "mayk.britomail.com"
}

### 400 InviteParticipantRequestPayload 1
POST http://localhost:8080/trips/{{tripId}}/invites
Content-Type: application/json

{
  "email": ""
}

### 400 InviteParticipantRequestPayload 2
POST http://localhost:8080/trips/{{tripId}}/invites
Content-Type: application/json

{
  "email": "mayk.britomail.com"
}

### 400 ActivityRequestPayload 1
POST http://localhost:8080/trips/{{tripId}}/activities
Content-Type: application/json

{
  "title": "",
  "occurs_at": ""
}

### 400 ActivityRequestPayload 2
POST http://localhost:8080/trips/{{tripId}}/activities
Content-Type: application/json

{
  "title": "Check-in no hotel",
  "occurs_at": "2024-07-15T12:00:00Z"
}

### 400 ActivityRequestPayload 3
POST http://localhost:8080/trips/{{tripId}}/activities
Content-Type: application/json

{
  "title": "Check-out no hotel",
  "occurs_at": "2024-07-31T12:00:00Z"
}

### 400 LinkRequestPayload 1
POST http://localhost:8080/trips/{{tripId}}/links
Content-Type: application/json

{
  "title": "",
  "url": ""
}

### 400 LinkRequestPayload 2
POST http://localhost:8080/trips/{{tripId}}/links
Content-Type: application/json

{
  "title": "Hospedagem",
  "url": "invalid-url"
}
