services:
  mailpit:
    image: axllent/mailpit:v1.19.0
    restart: unless-stopped
    volumes:
      - mailpit:/data
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MP_DATABASE: /data/mailpit.db

volumes:
  mailpit:
    driver: local
