spring:
  application:
    name: planner-java
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: localhost
    port: 1025

planner:
  mail:
    sender: AlgaFood <dev.tests@email.com>
